# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

version: "3"
services:
  nginx:
    image: nginx
    container_name: msw_service_nginx_${TAG}
    volumes:
      - ../src/nginx/:/etc/nginx/conf.d/
      - ../cache/ssl/:/etc/nginx/ssl/
      - ../cache/nginx/:/var/log/nginx/
      - ../cache/angular/publish/repo/:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - service_network

  dotnet:
    image: msw.dotnet:publish
    container_name: msw_service_dotnet_${TAG}
    ports:
      - "5000:5000"
    networks:
      - service_network

  node:
    image: msw.node:publish
    container_name: msw_service_node_${TAG}
    ports:
      - "3000:3000"
    networks:
      - service_network

networks:
  service_network:
    driver: bridge
